// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {runner} from '../models';

export function AddProject(arg1:string):Promise<store.Project>;

export function AddScanned(arg1:Array<store.Project>):Promise<void>;

export function GetLogs(arg1:string):Promise<Array<string>>;

export function GetStatus(arg1:string):Promise<runner.Status>;

export function GetWorkspaces():Promise<Array<string>>;

export function ListProjects():Promise<Array<store.Project>>;

export function RemoveProject(arg1:string):Promise<void>;

export function ScanWorkspaces(arg1:Array<string>):Promise<Array<store.Project>>;

export function SetWorkspaces(arg1:Array<string>):Promise<void>;

export function StartProject(arg1:string):Promise<void>;

export function StopProject(arg1:string):Promise<void>;

export function UpdateProject(arg1:store.Project):Promise<void>;

export function UpdateProjectCommand(arg1:string,arg2:string):Promise<store.Project>;
