// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {docker} from '../models';
import {runner} from '../models';
import {main} from '../models';

export function AddProject(arg1:string):Promise<store.Project>;

export function AddScanned(arg1:Array<store.Project>):Promise<void>;

export function ClearLogs(arg1:string):Promise<void>;

export function ComposeDown(arg1:string):Promise<void>;

export function ComposeRestart(arg1:string,arg2:string):Promise<void>;

export function ComposeStop(arg1:string,arg2:string):Promise<void>;

export function ComposeUp(arg1:string,arg2:string):Promise<void>;

export function DockerAvailable():Promise<docker.Info>;

export function FollowComposeLogs(arg1:string,arg2:string):Promise<void>;

export function FollowContainerLogs(arg1:string):Promise<void>;

export function GetLogs(arg1:string):Promise<Array<string>>;

export function GetProjectBranch(arg1:string):Promise<string>;

export function GetStatus(arg1:string):Promise<runner.Status>;

export function GetWorkspaces():Promise<Array<string>>;

export function ListComposeServices(arg1:string):Promise<Array<docker.ComposeService>>;

export function ListContainers():Promise<Array<docker.ContainerState>>;

export function ListGroups():Promise<Array<store.LaunchGroup>>;

export function ListProjects():Promise<Array<store.Project>>;

export function PickDirectory():Promise<string>;

export function RemoveContainer(arg1:string,arg2:boolean):Promise<void>;

export function RemoveGroup(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function ResetProjects():Promise<void>;

export function RestartContainer(arg1:string):Promise<void>;

export function SaveGroup(arg1:store.LaunchGroup):Promise<store.LaunchGroup>;

export function ScanWorkspaces(arg1:Array<string>):Promise<Array<store.Project>>;

export function SetWorkspaces(arg1:Array<string>):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StartGroup(arg1:string):Promise<Array<main.LaunchResult>>;

export function StartProject(arg1:string):Promise<void>;

export function StartProjectCommand(arg1:string,arg2:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;

export function StopFollowComposeLogs(arg1:string,arg2:string):Promise<void>;

export function StopFollowContainerLogs(arg1:string):Promise<void>;

export function StopGroup(arg1:string):Promise<void>;

export function StopProject(arg1:string):Promise<void>;

export function StopProjectCommand(arg1:string,arg2:string):Promise<void>;

export function UpdateCancel():Promise<main.UpdateState>;

export function UpdateCheck():Promise<main.UpdateState>;

export function UpdateGetState():Promise<main.UpdateState>;

export function UpdateInstall():Promise<main.UpdateState>;

export function UpdateProject(arg1:store.Project):Promise<void>;

export function UpdateProjectCommand(arg1:string,arg2:string):Promise<store.Project>;

export function UpdateProjectCommands(arg1:string,arg2:string,arg3:Array<main.CommandInput>):Promise<store.Project>;

export function UpdateStartDownload():Promise<main.UpdateState>;
