// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddScanned(arg1) {
  return window['go']['main']['App']['AddScanned'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function ScanWorkspaces(arg1) {
  return window['go']['main']['App']['ScanWorkspaces'](arg1);
}

export function SetWorkspaces(arg1) {
  return window['go']['main']['App']['SetWorkspaces'](arg1);
}

export function StartProject(arg1) {
  return window['go']['main']['App']['StartProject'](arg1);
}

export function StopProject(arg1) {
  return window['go']['main']['App']['StopProject'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateProjectCommand(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectCommand'](arg1, arg2);
}
