// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddScanned(arg1) {
  return window['go']['main']['App']['AddScanned'](arg1);
}

export function ClearLogs(arg1) {
  return window['go']['main']['App']['ClearLogs'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetProjectBranch(arg1) {
  return window['go']['main']['App']['GetProjectBranch'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function RemoveGroup(arg1) {
  return window['go']['main']['App']['RemoveGroup'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function SaveGroup(arg1) {
  return window['go']['main']['App']['SaveGroup'](arg1);
}

export function ScanWorkspaces(arg1) {
  return window['go']['main']['App']['ScanWorkspaces'](arg1);
}

export function SetWorkspaces(arg1) {
  return window['go']['main']['App']['SetWorkspaces'](arg1);
}

export function StartGroup(arg1) {
  return window['go']['main']['App']['StartGroup'](arg1);
}

export function StartProject(arg1) {
  return window['go']['main']['App']['StartProject'](arg1);
}

export function StartProjectCommand(arg1, arg2) {
  return window['go']['main']['App']['StartProjectCommand'](arg1, arg2);
}

export function StopGroup(arg1) {
  return window['go']['main']['App']['StopGroup'](arg1);
}

export function StopProject(arg1) {
  return window['go']['main']['App']['StopProject'](arg1);
}

export function StopProjectCommand(arg1, arg2) {
  return window['go']['main']['App']['StopProjectCommand'](arg1, arg2);
}

export function UpdateCancel() {
  return window['go']['main']['App']['UpdateCancel']();
}

export function UpdateCheck() {
  return window['go']['main']['App']['UpdateCheck']();
}

export function UpdateGetState() {
  return window['go']['main']['App']['UpdateGetState']();
}

export function UpdateInstall() {
  return window['go']['main']['App']['UpdateInstall']();
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}

export function UpdateProjectCommand(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectCommand'](arg1, arg2);
}

export function UpdateProjectCommands(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProjectCommands'](arg1, arg2, arg3);
}

export function UpdateStartDownload() {
  return window['go']['main']['App']['UpdateStartDownload']();
}
